name: socket_io_dart
version: 0.0.1

description: A Dart implementation of the socket.io client and server.

homepage: https://github.com/wordcollector/socket_io_dart
repository: https://github.com/wordcollector/socket_io_dart
issue_tracker: https://github.com/wordcollector/socket_io_dart/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  test: ^1.21.4
  words: ^0.1.1