name: socket_io_dart
version: 0.1.0

description: A Dart implementation of the socket.io client and server.

homepage: https://github.com/wordcollector/socket_io_dart
repository: https://github.com/wordcollector/socket_io_dart
issue_tracker: https://github.com/wordcollector/socket_io_dart/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  fpdart: ^0.2.0

dev_dependencies:
  matcher: ^0.12.12
  test: ^1.21.4
  words: ^0.1.1
