publish_to: none

name: engine_io_dart
version: 0.0.1

description: A Dart implementation of the socket.io engine.

homepage: https://github.com/wordcollector/engine_io_dart
repository: https://github.com/wordcollector/engine_io_dart
issue_tracker: https://github.com/wordcollector/engine_io_dart/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  sprint: ^1.0.4

dev_dependencies:
  words: ^0.1.1
